version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/tasks

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"

